#!/usr/bin/python3
#elvin codes

def text_indentation(text):
    for i in text:
        if i == ':':
            i =  print()
            print()
        elif i == '?':
            print()
            print()
        elif i == '.':
            print()
            print()
        print(i, end="")
